site_name: CryptoCoinJS
site_url: http://cryptocoinjs.com
site_description: CryptoCoinJS Bitcoin and Crypto Currency JavaScript Library

repo_url: https://github.com/cryptocoinjs/

pages:
- ['index.md', 'About', 'Main']
- ['faq.md', 'About', 'FAQ']
- ['team.md', 'About', 'Team']

# Currency Modules (please alphabetize)
- ['modules/currency/coininfo.md', 'Currency Modules', 'coininfo - Crypto Currency Specific Information']
- ['modules/currency/coinkey.md', 'Currency Modules', 'coinkey - Private Keys / Addresses']
- ['modules/currency/coinstring.md', 'Currency Modules', 'coinstring - Create & Parse Addresses / WIF / Base58']
- ['modules/currency/eckey.md', 'Currency Modules', 'eckey - Private Keys / Elliptic Curve']

# Crypto Modules (please alphabetize)
- ['modules/crypto/aes.md', 'Crypto Modules', 'aes - Advanced Encryption Standard']
- ['modules/crypto/ecdsa.md', 'Crypto Modules', 'ecdsa - Elliptic Curve Signing / Verification']
- ['modules/crypto/ecurve.md', 'Crypto Modules', 'ecurve - Elliptic Curve Cryptography']
- ['modules/crypto/pbkdf2-sha256.md', 'Crypto Modules', 'pbkdf2-sha256 - PBKDF2 using SHA256 HMAC']
- ['modules/crypto/ripemd160.md', 'Crypto Modules', 'ripemd160 - RIPEMD160 hash']
- ['modules/crypto/scryptsy.md', 'Crypto Modules', 'scryptsy - Scrypt Key Derivation']

# Misc Modules (please alphabetize)
- ['modules/misc/binstring.md', 'Misc Modules', 'binstring - convert data types']

theme: flatly

docs_dir: 'markdown'
site_dir: './'
