site_name: CryptoCoinJS
site_url: http://cryptocoinjs.com
site_description: CryptoCoinJS Bitcoin and Crypto Currency JavaScript Library

repo_url: https://github.com/cryptocoinjs/

pages:
- ['index.md', 'Home']

# Currency Modules
- ['modules/coininfo.md', 'Currency Modules', 'coininfo - Crypto Currency Specific Information']
- ['modules/coinkey.md', 'Currency Modules', 'CoinKey - Private Keys / Addresses']
- ['modules/coinstring.md', 'Currency Modules', 'coinstring - Create & Parse Addresses / WIF / Base58']
- ['modules/ecdsa.md', 'Currency Modules', 'ECDSA - Elliptic Curve Signing / Verification']
- ['modules/eckey.md', 'Currency Modules', 'ECKey - Private Keys / Elliptic Curve']
- ['modules/ecurve.md', 'Currency Modules', 'ecurve - Elliptic Curve Cryptography']

# Crypto Modules
- ['modules/aes.md', 'Crypto Modules', 'AES - Advanced Encryption Standard']

# Misc
- ['faq.md', 'FAQ']
- ['team.md', 'Team']

theme: flatly

docs_dir: 'markdown'
site_dir: './'
