site_name: CryptoCoinJS
site_url: http://cryptocoinjs.com
site_description: CryptoCoinJS Bitcoin and Crypto Currency JavaScript Library

repo_url: https://github.com/cryptocoinjs/

pages:
- ['index.md', 'About', 'Main']
- ['faq.md', 'About', 'FAQ']
- ['team.md', 'About', 'Team']

# Guide
- ['guide/getting-started.md', 'Guide', 'Getting Started']

# Currency Modules (please alphabetize)
- ['modules/currency/bip38.md', 'Currency Modules', 'bip38 - Password encrypted private keys']
- ['modules/currency/btc-p2p.md', 'Currency Modules', 'btc-p2p - Manage a network of peers in a Bitcoin p2p network']
- ['modules/currency/coininfo.md', 'Currency Modules', 'coininfo - Crypto Currency Specific Information']
- ['modules/currency/coinkey.md', 'Currency Modules', 'coinkey - Private Keys / Addresses']
- ['modules/currency/coinstring.md', 'Currency Modules', 'coinstring - Create & Parse Addresses / WIF / Base58']
- ['modules/currency/eckey.md', 'Currency Modules', 'eckey - Private Keys / Elliptic Curve']
- ['modules/currency/p2p-manager.md', 'Currency Modules', 'p2p-manager - Manage a network of peers in a p2p network']
- ['modules/currency/p2p-node.md', 'Currency Modules', 'p2p-node - Handle p2p traffic on crypto currency networks']

# Curreny Modules that Need Documentation TLC
- ['modules/currency/btc-address.md', 'Currency Modules', 'btc-address - Bitcoin Address Handling']
- ['modules/currency/btc-opcode.md', 'Currency Modules', 'btc-opcode - Bitcoin Opcodes']
- ['modules/currency/btc-script.md', 'Currency Modules', 'btc-script - Bitcoin Script']
- ['modules/currency/btc-scriptinterpreter.md', 'Currency Modules', 'btc-scriptinterpreter - Bitcoin Script Interpreter']
- ['modules/currency/btc-transaction.md', 'Currency Modules', 'btc-transaction - Bitcon Transaction Creation / Parsing']


# Crypto Modules (please alphabetize)
- ['modules/crypto/aes.md', 'Crypto Modules', 'aes - Advanced Encryption Standard']
- ['modules/crypto/crypto-hashing.md', 'Crypto Modules', 'crypto-hashing - Normalized interface to hash functions']
- ['modules/crypto/ecdsa.md', 'Crypto Modules', 'ecdsa - Elliptic Curve Signing / Verification']
- ['modules/crypto/ecurve.md', 'Crypto Modules', 'ecurve - Elliptic Curve Cryptography']
- ['modules/crypto/pbkdf2-sha256.md', 'Crypto Modules', 'pbkdf2-sha256 - PBKDF2 using SHA256 HMAC']
- ['modules/crypto/ripemd160.md', 'Crypto Modules', 'ripemd160 - RIPEMD160 hash']
- ['modules/crypto/scryptsy.md', 'Crypto Modules', 'scryptsy - Scrypt Key Derivation']
- ['modules/crypto/sha512.md', 'Crypto Modules', 'sha512 - SHA 512 Secure Hashing Algorithm']

# Misc Modules (please alphabetize)
- ['modules/misc/bigi.md', 'Misc Modules', 'bigi - Big Integers']
- ['modules/misc/binstring.md', 'Misc Modules', 'binstring - Convert data types']
- ['modules/misc/bs58.md', 'Misc Modules', 'bs58 - BASE58 encoding / decoding']
- ['modules/misc/qr-encode.md', 'Misc Modules', 'qr-encode - Encode data into QR']

theme: flatly

docs_dir: 'markdown'
site_dir: './'
