site_name: CryptoCoinJS
site_url: http://cryptocoinjs.com
site_description: CryptoCoinJS Bitcoin and Crypto Currency JavaScript Library

repo_url: https://github.com/cryptocoinjs/

pages:
- ['index.md', 'Home']

# Currency Modules (please alphabetize)
- ['modules/currency/coininfo.md', 'Currency Modules', 'coininfo - Crypto Currency Specific Information']
- ['modules/currency/coinkey.md', 'Currency Modules', 'coinkey - Private Keys / Addresses']
- ['modules/currency/coinstring.md', 'Currency Modules', 'coinstring - Create & Parse Addresses / WIF / Base58']
- ['modules/currency/eckey.md', 'Currency Modules', 'ecKey - Private Keys / Elliptic Curve']

# Crypto Modules (please alphabetize)
- ['modules/crypto/aes.md', 'Crypto Modules', 'aes - Advanced Encryption Standard']
- ['modules/crypto/ecdsa.md', 'Crypto Modules', 'ecdsa - Elliptic Curve Signing / Verification']
- ['modules/crypto/ecurve.md', 'Crypto Modules', 'ecurve - Elliptic Curve Cryptography']

# Misc Modules (please alphabetize)

# Misc
- ['faq.md', 'FAQ']
- ['team.md', 'Team']

theme: flatly

docs_dir: 'markdown'
site_dir: './'
